"""initial core loop schema

Revision ID: 468f4134bb21
Revises:
Create Date: 2026-08-29 10:54:52.381067
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "468f4134bb21"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor_id", "scope", "key"),
    )
    op.create_index(op.f("ix_idempotency_records_actor_id"), "idempotency_records", ["actor_id"], unique=False)
    op.create_table(
        "item_definitions",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("rarity", sa.String(length=20), nullable=False),
        sa.Column("item_type", sa.String(length=40), nullable=False),
        sa.Column("power", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_definitions_rarity"), "item_definitions", ["rarity"], unique=False)
    op.create_table(
        "quest_definitions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("primary_stat", sa.String(length=3), nullable=False),
        sa.Column("objective", sa.JSON(), nullable=False),
        sa.Column("verification_policy", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("auth_provider_id", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_provider_id"),
    )
    op.create_table(
        "player_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("current_xp", sa.Integer(), nullable=False),
        sa.Column("str_stat", sa.Integer(), nullable=False),
        sa.Column("agi", sa.Integer(), nullable=False),
        sa.Column("vit", sa.Integer(), nullable=False),
        sa.Column("int_stat", sa.Integer(), nullable=False),
        sa.Column("wil", sa.Integer(), nullable=False),
        sa.Column("streak_days", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("current_xp >= 0"),
        sa.CheckConstraint("level >= 1"),
        sa.CheckConstraint("str_stat >= 0 AND agi >= 0 AND vit >= 0 AND int_stat >= 0 AND wil >= 0"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_player_profiles_user_id"), "player_profiles", ["user_id"], unique=True)
    op.create_table(
        "player_quests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("quest_definition_id", sa.String(length=80), nullable=False),
        sa.Column("quest_definition_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_definition_id"],
            ["quest_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_player_quests_player_id"), "player_quests", ["player_id"], unique=False)
    op.create_table(
        "quest_submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("player_quest_id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("evidence_type", sa.String(length=20), nullable=False),
        sa.Column("manual_evidence", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_quest_id"],
            ["player_quests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "idempotency_key"),
    )
    op.create_index(op.f("ix_quest_submissions_player_id"), "quest_submissions", ["player_id"], unique=False)
    op.create_index(
        op.f("ix_quest_submissions_player_quest_id"), "quest_submissions", ["player_quest_id"], unique=False
    )
    op.create_table(
        "reward_grants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("rules_version", sa.String(length=30), nullable=False),
        sa.Column("exp_granted", sa.Integer(), nullable=False),
        sa.Column("stat_changes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["quest_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id"),
    )
    op.create_index(op.f("ix_reward_grants_player_id"), "reward_grants", ["player_id"], unique=False)
    op.create_table(
        "verification_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("extracted_facts", sa.JSON(), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["quest_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id"),
    )
    op.create_table(
        "chests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("reward_grant_id", sa.String(length=36), nullable=False),
        sa.Column("rarity", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rng_version", sa.String(length=30), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reward_grant_id"],
            ["reward_grants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reward_grant_id"),
    )
    op.create_index(op.f("ix_chests_player_id"), "chests", ["player_id"], unique=False)
    op.create_table(
        "progression_ledger",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("reward_grant_id", sa.String(length=36), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("stat_name", sa.String(length=3), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reward_grant_id"],
            ["reward_grants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reward_grant_id", "entry_type", "stat_name"),
    )
    op.create_index(op.f("ix_progression_ledger_player_id"), "progression_ledger", ["player_id"], unique=False)
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("item_definition_id", sa.String(length=100), nullable=False),
        sa.Column("item_definition_version", sa.Integer(), nullable=False),
        sa.Column("source_chest_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_definition_id"],
            ["item_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_chest_id"],
            ["chests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_chest_id"),
    )
    op.create_index(op.f("ix_inventory_items_player_id"), "inventory_items", ["player_id"], unique=False)
    op.create_table(
        "chest_open_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chest_id", sa.String(length=36), nullable=False),
        sa.Column("item_instance_id", sa.String(length=36), nullable=False),
        sa.Column("rng_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chest_id"],
            ["chests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_instance_id"],
            ["inventory_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chest_id"),
        sa.UniqueConstraint("item_instance_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chest_open_results")
    op.drop_index(op.f("ix_inventory_items_player_id"), table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_index(op.f("ix_progression_ledger_player_id"), table_name="progression_ledger")
    op.drop_table("progression_ledger")
    op.drop_index(op.f("ix_chests_player_id"), table_name="chests")
    op.drop_table("chests")
    op.drop_table("verification_results")
    op.drop_index(op.f("ix_reward_grants_player_id"), table_name="reward_grants")
    op.drop_table("reward_grants")
    op.drop_index(op.f("ix_quest_submissions_player_quest_id"), table_name="quest_submissions")
    op.drop_index(op.f("ix_quest_submissions_player_id"), table_name="quest_submissions")
    op.drop_table("quest_submissions")
    op.drop_index(op.f("ix_player_quests_player_id"), table_name="player_quests")
    op.drop_table("player_quests")
    op.drop_index(op.f("ix_player_profiles_user_id"), table_name="player_profiles")
    op.drop_table("player_profiles")
    op.drop_table("users")
    op.drop_table("quest_definitions")
    op.drop_index(op.f("ix_item_definitions_rarity"), table_name="item_definitions")
    op.drop_table("item_definitions")
    op.drop_index(op.f("ix_idempotency_records_actor_id"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    # ### end Alembic commands ###
